### ISSUE TITLE
Question About Using cluster_list[1:4] in find_markers_parallel

### ISSUE THREAD

**Issue by Georgewwek** [yanailab/drug-resistance#1]
You've done an amazing job with this project! 🌟 Thanks for your great work and for making this available to everyone! However，

I have a quick question about this line: 
signatures = find_markers_parallel(kura_all, cluster_list[1:4], ncores = 4). I'm curious about the purpose of using [1:4] in cluster_list. Why not use the entire cluster_list?

I really appreciate the effort and generosity in sharing this code with the community

**Comment by gufranca** [comment]
Dear George, Thank you for your message and kind words! Thanks also for pointing this out. I believe that I left cluster_list[1:4] by mistake as it was just for testing purposes. You are correct, it should be then entire cluster_list. I will fix it.
