### ISSUE TITLE
Availability of Processed Data

### ISSUE THREAD

**Issue by psl-schaefer** [yanailab/drug-resistance#2]
Thanks for doing this amazing work!

I was wondering if processed data objects (e.g., count matrices, Seurat objects, etc.) are available for download? I could only find links to the raw data (FASTQ files) in the paper, and if possible, I’d like to avoid redoing the preprocessing.

Thank you in advance for your help!

Best 
Philipp

**Comment by gufranca** [comment]
Dear Philipp,
Thank you for your interest in our work. Yes, you can download the processed data (count data) from each data/experiment from their respective SubSeries in https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE247691 (Ex: GSE206125, GSE247684, etc). I hope this helps.
Best,
Gustavo

**Comment by gufranca** [comment]
> Thanks for doing this amazing work!
> 
> I was wondering if processed data objects (e.g., count matrices, Seurat objects, etc.) are available for download? I could only find links to the raw data (FASTQ files) in the paper, and if possible, I’d like to avoid redoing the preprocessing.
> 
> Thank you in advance for your help!
> 
> Best Philipp

Dear Philipp,
Thank you for your interest in our work. Yes, you can download the processed data (count data) from each data/experiment from their respective SubSeries in https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE247691 (Ex: GSE206125, GSE247684, etc). I hope this helps.
Best,
Gustavo

**Comment by psl-schaefer** [comment]
Thanks a lot for responding so quickly @gufranca! Got the data that I was interested in! Have a nice day :)
