### ISSUE TITLE
Where can I find the gene_filter() function used in filter_signatures()?

### ISSUE THREAD

**Issue by lucagu1965** [yanailab/drug-resistance#3]
Hello,
I’ve been reviewing the code for `filter_signatures()` and noticed that it calls a function named `gene_filter() (line genes_data = gene_filter(as.matrix(genes_data), exp_level = min_exp_sig, n_samples = 10))`. However, I couldn’t find any definition or documentation for `gene_filter()` in this repository or in the related code. Could you please let me know where this function is defined, or provide the code for it? Understanding what `gene_filter()` does and its expected input/output is essential for reproducing the analysis.
Thank you in advance.

**Comment by gufranca** [comment]
> Hello, I’ve been reviewing the code for `filter_signatures()` and noticed that it calls a function named `gene_filter() (line genes_data = gene_filter(as.matrix(genes_data), exp_level = min_exp_sig, n_samples = 10))`. However, I couldn’t find any definition or documentation for `gene_filter()` in this repository or in the related code. Could you please let me know where this function is defined, or provide the code for it? Understanding what `gene_filter()` does and its expected input/output is essential for reproducing the analysis. Thank you in advance.

Apologies for the missing code. I added a file 'filter_gene_expression.R' which contains `gene_filter()`. It is a function to simply filter out genes that are expressed lower than a threshold (exp_level) in less than a number of samples/cells (n_samples). The input is expression matrix with genes as rows and cells as columns and it returns an expression matrix with genes filtered out. The code is:
```
gene_filter <- function(exp_matrix, exp_level=1, n_samples=1) {
  # subsets the raw data matrix to keep only expressed genes
  # Like removing the "bad rows"
  # Args:
  #   dataset: the original gene expression matrix read in
  #   exp_level: threshold for minimum expression level (default = 1)
  #   n_samples: threshold for minimum n of samples with exp_level (default = 1)
  
  exp_matrix = exp_matrix[rowSums(exp_matrix > exp_level) >= n_samples, ]
  # just an alert if no rows matches the criteria
  if (nrow(exp_matrix) == 0) {
    print("Empty Rows! No rows matched the criteria.")
  }
  return(exp_matrix)
}
```
Best,
Gu

**Comment by lucagu1965** [comment]
Thank you so much for the quick response and for adding the file @gufranca. Have a nice day :)
